#!/bin/sh

### BEGIN INIT INFO
# Provides: apache
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: apache initscript
# Description: This file should be used to construct scripts to be apache
# placed in /etc/init.d.
### END INIT INFO


case "$1" in
	start)
		if [ -x /usr/local/apache/bin/apachectl ]; then
			echo -n ' tomcat'; /usr/local/apache/bin/apachectl start
		fi
	;;
	stop)
		/usr/local/apache/bin/apachectl stop
	;;
	*)
		echo "Usage {start|stop}"
	exit 1 ;;
esac

exit 0
