#!/bin/sh

### BEGIN INIT INFO
# Provides: proftpd
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: proftpd initscript
# Description: This file should be used to construct scripts to be proftpd
# placed in /etc/init.d.
### END INIT INFO


case "$1" in
        start)
                if [ -x /usr/local/proftpd/sbin/in.proftpd ]; then
                        echo -n ' proftpd'; /usr/local/proftpd/sbin/in.proftpd
                fi
        ;;
        stop)
                pkill -9 -ef proftpd
        ;;
        *)
                echo "Usage {start|stop}"
        exit 1 ;;
esac

exit 0
