#!/bin/sh

### BEGIN INIT INFO
# Provides: named 
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: named  initscript
# Description: This file should be used to construct scripts to be named
# placed in /etc/init.d.
### END INIT INFO


case "$1" in
        start)
                if [ -x /usr/local/bind9/sbin/named ]; then
                        echo -n ' named'; /usr/local/bind9/sbin/named &
                fi
        ;;
        stop)
                pkill -9 -ef named
        ;;
        *)
                echo "Usage {start|stop}"
        exit 1 ;;
esac

exit 0
